name: BuildContainerImage

on:
  push:
    branches: 
      - 'master'
      - 'release-*'
    tags: 
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push docker images
        if: github.event_name == 'push'
        run: |
          REPO=registry.cn-beijing.aliyuncs.com/kubesphereio TAG="${GITHUB_REF#refs/*/}" make container-cross-push
          REPO=kubesphere TAG="${GITHUB_REF#refs/*/}" make container-cross-push
